package.json, src/components/Row/index.js, src/components/Row/styles.js, src/index.js, yarn.lock
=> feat(src): add Row component

src/components/Col/index.js, src/components/Col/styles.js, src/index.js
=> feat(src): add Col component

src/index.js
feat(index): add getFontAwesome
=> feat(index): add getFontAwesome

README.md, src/components/Button/index.js, src/components/Button/styles.js, src/index.js
feat(src): add Button component and fix title in README
=> feat(src): add Button component and fix title in README

src/components/Header/NavItem.js, src/components/Header/index.js, src/components/Header/styles.js
style(header): style header and create NavItem component
=> style(header): style header and create NavItem component

src/components/SignIn/index.js, src/components/SignIn/styles.js
style(signin): correct the home screen
=> style(signIn): correct signIn styles

services/package.json, src/sagas/session.js, src/services/index.js, src/services/storage.js
feat(services): add storage service
=> feat(services): add storage service

src/services/storage.js
fix(storage): fix when has empty keys change null to array
=> fix(storage): fix when has empty keys change null to array

src/components/Title/index.js, src/components/Title/styles.js, src/index.js
feat(title): add Title component
=> feat(title): add Title component

src/components/Header/index.js
fix(header): show NavItem when has token
=> fix(header): hide nav when user has no session

src/components/Grid/index.js, src/components/childrenPropType.js, src/index.js
fix(grid): fix when children is array
=> fix(grid): fix Grid when children is one element

src/actions/index.js
fix(actions): export handleError action
=> fix(actions): export handleError action

src/components/Col/index.js, src/components/Grid/index.js, src/components/Header/NavItem.js, src/components/Row/index.js, src/components/SignIn/index.js, src/components/getFontAwesome.js, src/index.js
fix(grid): fix when import childrenPropType
=> fix(components): fix import components from same package

src/components/SignIn/styles.js
=> style(signIn): center login on screen

src/components/Title/styles.js
style(titleStyle): left margin change
=> style(title): style left margin

src/components/Header/index.js, src/components/Header/styles.js
feat(header): add Image for new logo
=> feat(header): add rightImage on Header component

src/components/Header/index.js
fix(header): change propType oneOf to oneOfType
=> fix(header): fix propTypes for images on header

src/components/SignIn/index.js, src/components/SignIn/styles.js, src/util/imagePropType/index.js, src/util/imagePropType/index.web.js
style(signin): logo of the incorporated national agency
=> style(signIn): add optional image on SignIn component

src/services/storage.js
add docs for the StorageService
=> fix(storage): support receive one ID to remove

src/components/Alert/index.js, src/components/Alert/styles.js, src/index.js, yarn.lock
style(alert): create alert component
=> feat(alert): add Alert component

src/components/SignIn/index.js
fix(signIn): fix when add new line in the message
=> fix(signIn): fix default changeUserText warning line feed

src/services/dateUtils.js, src/services/index.js
feat(services): add dateUtilsService
=> feat(services): add dateUtilsService

src/util/stylePropType.js
refactor(stylePropType): add bool to oneOfType
=> refactor(util): add boolean support to stylePropType

src/services/session.js
if token is `null` this code `!(token instanceof Error)` return `true` and sagas check if user is logged and does not report invalid user or password.
=> fix(session): fix check session token on sign in

.huskyrc.json, .travis.yml, package-lock.json, package.json
upgrade react-native@0.57.5, eslint@5.9.0, husky@1.2.0
=> fix(packages): upgrade react to v16.6.3

package-lock.json, package.json, src/actions/index.js, src/actions/session.js, src/components/Header/NavItem.js, src/components/SignIn/ChangeUserMessage.js, src/components/SignIn/ErrorLoginMessages.js, src/components/SignIn/index.js, src/reducers/session.js, src/sagas/index.js, src/sagas/session.js, src/services/session.js
refactor(package): add refresh token
=> feat(session): add fetch refresh token on login

package-lock.json, package.json, src/actions/session.js, src/components/SignIn/ChangeUserMessage.js, src/components/SignIn/ErrorLoginMessages.js, src/components/SignIn/index.js, src/reducers/session.js, src/services/session.js
refactor(session): move logic to service
=> refactor(session): move logic to service

src/reducers/session.js
fix(session): set user invalid when clean user validations
=> fix(session): set user invalid when clean user validations

src/components/Header/Brand.js, src/components/Header/styles.js
style(brand): change position to app text and version
=> style(brand): change position to app text and version

src/reducers/session.js
fix(session): set user invalid when login failed
=> fix(session): set user invalid when login failed
